#define LCREDIT "lcredit=-1\n"
#define UCREDIT "ucredit=-1\n"
#define DCREDIT "dcredit=-1\n"
#define OCREDIT "ocredit=-1\n"
#define MINLEN  "minlen=8\n"
#define RETRY   "retry=3\n"

#include "DeleteSpace.c"
#include "homeDir.c"

#include "U_01.c"
#include "U_02.c"
#include "U_03.c"
#include "U_04.c"
#include "U_05.c"
#include "U_06.c"
#include "U_07.c"
#include "U_08.c"
#include "U_09.c"
#include "U_10.c"
#include "U_11.c"
#include "U_12.c"
#include "U_13.c"
#include "U_14.c"
#include "U_15.c"
#include "U_16.c"
#include "U_17.c"
#include "U_18.c"
#include "U_19.c"
#include "U_20.c"
#include "U_21.c"
#include "U_22.c"
#include "U_23.c"
#include "U_24.c"
#include "U_25.c"
#include "U_26.c"
#include "U_27.c"
#include "U_28.c"
#include "U_29.c"
#include "U_30.c"
#include "U_31.c"
#include "U_32.c"
#include "U_33.c"
#include "U_34.c"
#include "U_35.c"
#include "U_36.c"
#include "U_37.c"
#include "U_38.c"
#include "U_39.c"
#include "U_40.c"
#include "U_41.c"
#include "U_42.c"
#include "U_43.c"
#include "U_44.c"
#include "U_45.c"
#include "U_46.c"
#include "U_47.c"
#include "U_48.c"
#include "U_49.c"
#include "U_50.c"
#include "U_51.c"
#include "U_52.c"
#include "U_53.c"
#include "U_54.c"
#include "U_55.c"
#include "U_56.c"
#include "U_57.c"
#include "U_58.c"
#include "U_59.c"
#include "U_60.c"
#include "U_61.c"
#include "U_62.c"
#include "U_63.c"
#include "U_64.c"
#include "U_65.c"
#include "U_66.c"
#include "U_67.c"
#include "U_68.c"
#include "U_69.c"
#include "U_70.c"
#include "U_71.c"
#include "U_72.c"
#include "U_73.c"
